### ISSUE TITLE
Wrong git path?

### ISSUE THREAD

**Issue by alfa756** [xmflsct/yi-hack-1080p#1]
The path for 1080p hack is the same as 720p camera and therefore does not work on 1080p version. Could you please post the correct git path? Thank you

**Comment by xmflsct** [comment]
They are not the same, if you look into detail file structures, etc. However I haven't been able to get RTSP server working yet, so only FTP and Telnet are working.

**Comment by Orlandus** [comment]
Hi. Can you give me advice how to use this camera (xiaomi yi 1080p upgrade to v1) not in China?

**Comment by xmflsct** [comment]
@Orlandus How do you want to use it? With official app? Or through custom RTSP stream?

**Comment by Orlandus** [comment]
@xmflsct with official app

**Comment by xmflsct** [comment]
@Orlandus Then I am not sure. I read somewhere that if you had previously associated the cam with the app, after blocking verification request, you can still connect to the app. But I haven't tried that myself. But if you haven't, then you probably cannot do it anymore.

**Comment by Orlandus** [comment]
@xmflsct you want to say that i can't use it and there is no any variants?

**Comment by xmflsct** [comment]
@Orlandus As far as I know, it is almost impossible to use it with the official app. But feel free to read how what other people said in the original yi-hack project and internet. I am working on a custom RTSP server for 1080p version, which is the way I wanted to have the camera to work.

**Comment by Orlandus** [comment]
@xmflsct it's very sad :( i bought this camera accidentally instead of 720p version :((
can you give advice how use RTSP on it?

**Comment by xmflsct** [comment]
@Orlandus Not yet, as I am still working on it, and I did not find another other project working on it yet.

**Comment by Orlandus** [comment]
@xmflsct thanks for your answers. I hope somebody will hack this :(

**Comment by xmflsct** [comment]
@Orlandus I have just push an update. Now an RTSP stream of 720p is possible.
