### ISSUE TITLE
Trying to dump rtsp to file with ffmpeg

### ISSUE THREAD

**Issue by jbmfg** [xmflsct/yi-hack-1080p#11]
Tried several commands but always get:

[rtsp @ 0x561e3df07ee0] method SETUP failed: 461 Unsupported transport
rtsp://192.168.0.252/ch0_0.h264:554: Protocol not supported

What transport & protocol should i be using?  Tried forcing TCP and UDP but to no avail

**Comment by xmflsct** [comment]
The RTSP support in this project is in early experimental stage, but not in development anymore. Please refer to [](https://github.com/shadow-1/yi-hack-v3) for further developments in RTSP support.
