### ISSUE TITLE
firmware filename

### ISSUE THREAD

**Issue by maysamsh** [xmflsct/yi-hack-1080p#4]
finename for this revision should be home_y20. 
I have tried https://github.com/xmflsct/yi-hack-1080p/issues/3#issuecomment-289458681 but seems the cam is broken. it blinked for about 20 seconds then turned into still yellow, even reset does not work.

**Comment by xmflsct** [comment]
Yes you are correct. But I don't provide any firmware for upgrade of downgrade as a way to hack it.

**Comment by maysamsh** [comment]
Someone did, but it does not work.
