### ISSUE TITLE
RTSP 720p video is crop from 1080p video?

### ISSUE THREAD

**Issue by GuryYu** [xmflsct/yi-hack-1080p#8]
Video form rtsp 720p is much smaller than 1080p video ,it looks like crop from 1080p video. The general approach is to scale from 1080p video.Is it a bug?
By the way, infrared night vision can't be used either.

**Comment by xmflsct** [comment]
It is not a bug. The current RTSP server is an early test version created by @andy2301, which interfaces directly with the hardware itself. This won't be the path that we are going further.

Currently, @andy2301 and @shadow-1 are working hard on a different approach that takes data directly from those that are generated by the official application (which also takes care of night vision, etc.). Till then, this project serves only as a testbed.
